//ATIVIDADE 01
fun main() {

    val nome: String = "Maria Eduarda"
    var idade: Int = 18
    var altura: Double = 1.60
    var ehEstudante: Boolean = false

    println("Nome: $nome")
    println("Idade: $idade anos")
    println("Altura: $altura metros")
    println("É estudante? $ehEstudante")

    idade = 19
    altura = 1.64
    ehEstudante = true


    println("\n--- Informações Atualizadas ---")
    println("Nome: $nome")
    println("Idade: $idade anos")
    println("Altura: $altura metros")
    println("É estudante? $ehEstudante")
}
